on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: plan
        run: echo plan

  apply:
    runs-on: ubuntu-latest
    environment: lab
    steps:
      - name: apply
        run: echo applying now
